kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: rook-local
  annotations:
    argocd.argoproj.io/sync-wave: "1"
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rook-pv
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  capacity:
    storage: 200Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: rook-local
  local:
    path: /var/kube/rook-local
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - archon
